name: Run unit tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: cern-nextgen-h100
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-wrapper:latest
    steps:
      - uses: actions/checkout@v4
      - name: nvidia-smi
        run: |
          nvidia-smi
