name: Run unit tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: cern-nextgen-h100
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-wrapper@sha256:3453bacbd28c3aa0cec4051e28a80181120cd451abd2f5b00d890a220aa75b31
    steps:
      - uses: actions/checkout@v4
      - name: nvidia-smi
        run: |
          nvidia-smi
      - name: configure
        run: |
          CXX=clang++ CC=clang NVCC_CCBIN=clang CUDACXX=nvcc cmake -B ${{github.workspace}}/build
      - name: build
        run: |
          cmake --build ${{github.workspace}}/build
      - name: test
        run: |
          ctest --test-dir ${{github.workspace}}/build/tests --output-on-failure
