name: Run unit tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: cern-nextgen-h100
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-wrapper:latest
    steps:
      - uses: actions/checkout@v4
      - name: nvidia-smi
        run: |
          nvidia-smi
      - name: configure
        run: |
          CXX=clang++-18 CC=clang-18 NVCC_CCBIN=clang-18 CUDACXX=nvcc cmake -B ${{github.workspace}}/build
      - name: build
        run: |
          cmake --build ${{github.workspace}}/build
      - name: test
        run: |
          ctest --test-dir ${{github.workspace}}/build --output-on-failure
