name: Run unit tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    runs-on: cern-nextgen-h100
    container: registry.cern.ch/ngt-wp1.7/wp1.7-soa-wrapper@sha256:16432eae6635379637e67c4cc00334c46b6dce845b83da7e75fb754d24266897
    steps:
      - uses: actions/checkout@v4
      - name: cpu_gcc
        env:
          CXX: g++
          CC: gcc
          TEST_DIR: tests/cpu
        run: |
          cmake -B ${{github.workspace}}/build/${TEST_DIR}
          cmake --build ${{github.workspace}}/build/${TEST_DIR}
          ctest --test-dir ${{github.workspace}}/build/${TEST_DIR} --output-on-failure
          rm -rf ${{github.workspace}}/build
      - name: cpu_clang
        env:
          CXX: clang++
          CC: clang
          TEST_DIR: tests/cpu
        run: |
          cmake -B ${{github.workspace}}/build/${TEST_DIR}
          cmake --build ${{github.workspace}}/build/${TEST_DIR}
          ctest --test-dir ${{github.workspace}}/build/${TEST_DIR} --output-on-failure
          rm -rf ${{github.workspace}}/build
      - name: gpu_gcc
        env:
          CXX: g++
          CC: gcc
          NVCC_CCBIN: gcc
          CUDACXX: nvcc
          TEST_DIR: tests/gpu
        run: |
          nvidia-smi
          cmake -B ${{github.workspace}}/build/${TEST_DIR}
          cmake --build ${{github.workspace}}/build/${TEST_DIR}
          ctest --test-dir ${{github.workspace}}/build/${TEST_DIR} --output-on-failure
          rm -rf ${{github.workspace}}/build
      - name: gpu_clang
        env:
          CXX: clang++
          CC: clang
          NVCC_CCBIN: clang
          CUDACXX: nvcc
          TEST_DIR: tests/gpu
        run: |
          nvidia-smi
          cmake -B ${{github.workspace}}/build/${TEST_DIR}
          cmake --build ${{github.workspace}}/build/${TEST_DIR}
          ctest --test-dir ${{github.workspace}}/build/${TEST_DIR} --output-on-failure
          rm -rf ${{github.workspace}}/build
